

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chameleons?serverTimezone=UTC
    username: root
    password: tshishi
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    open-in-view: true

server:
  port: 8081
