version: '3.8'
services:
  database:
    image: 'mariadb:10.4'
    container_name: chameleons
    restart: always
    environment:
      MYSQL_DATABASE: chameleons
      MYSQL_ROOT_PASSWORD: tshishi
    ports:
      - '3306:3306'
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
